export type ResourceType =
  | "Official Documentation"
  | "YouTube Tutorial"
  | "Article"
  | "Online Course"
  | "Coding Challenge"
  | "Practice Platform";

export type LearningResource = {
  id: string;
  thumbnail: string;
  title: string;
  source: string;
  type: ResourceType;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estimatedTime: string;
  url: string;
  technologies: string[];
  description: string;
};

export const learningResources: LearningResource[] = [
  {
    id: "mdn-web-foundations",
    thumbnail: "/images/skillforge/features-ethereal-waves-light.png",
    title: "Learn Web Development",
    source: "MDN Web Docs",
    type: "Online Course",
    difficulty: "Beginner",
    estimatedTime: "12 hours",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
    technologies: ["HTML", "CSS", "JavaScript"],
    description: "Structured foundations for semantic HTML, modern CSS, and browser JavaScript.",
  },
  {
    id: "javascript-guide",
    thumbnail: "/images/skillforge/empty-learning-journey.png",
    title: "JavaScript Guide",
    source: "MDN Web Docs",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "6 hours",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    technologies: ["JavaScript"],
    description: "A dependable reference for language fundamentals, objects, promises, and modules.",
  },
  {
    id: "react-learn",
    thumbnail: "/images/skillforge/hero-ethereal-ai-light.png",
    title: "Learn React",
    source: "React",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "8 hours",
    url: "https://react.dev/learn",
    technologies: ["React", "JavaScript"],
    description: "The official interactive path through components, state, effects, and reusable logic.",
  },
  {
    id: "typescript-handbook",
    thumbnail: "/images/skillforge/footer-ethereal-constellation-light.png",
    title: "TypeScript Handbook",
    source: "TypeScript",
    type: "Official Documentation",
    difficulty: "Intermediate",
    estimatedTime: "7 hours",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    technologies: ["TypeScript"],
    description: "Core TypeScript concepts, narrowing, generics, modules, and type design.",
  },
  {
    id: "nextjs-course",
    thumbnail: "/images/skillforge/dashboard-ethereal-banner-light.png",
    title: "Learn Next.js",
    source: "Vercel",
    type: "Online Course",
    difficulty: "Intermediate",
    estimatedTime: "10 hours",
    url: "https://nextjs.org/learn",
    technologies: ["Next.js", "React", "TypeScript"],
    description: "Build a production-style application while learning routing, data, and rendering.",
  },
  {
    id: "tanstack-query-docs",
    thumbnail: "/images/skillforge/chat-subtle-neural-grid-light.png",
    title: "TanStack Query Overview",
    source: "TanStack",
    type: "Official Documentation",
    difficulty: "Intermediate",
    estimatedTime: "90 minutes",
    url: "https://tanstack.com/query/latest/docs/framework/react/overview",
    technologies: ["React", "TanStack Query"],
    description: "Server-state caching, mutations, invalidation, and asynchronous UI patterns.",
  },
  {
    id: "node-learn",
    thumbnail: "/images/skillforge/features-ethereal-waves.png",
    title: "Introduction to Node.js",
    source: "Node.js",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "4 hours",
    url: "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    technologies: ["Node.js", "JavaScript"],
    description: "Runtime fundamentals, asynchronous programming, files, HTTP, and packages.",
  },
  {
    id: "express-guide",
    thumbnail: "/images/skillforge/footer-ethereal-constellation.png",
    title: "Express Starter Guide",
    source: "Express",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "2 hours",
    url: "https://expressjs.com/en/starter/installing.html",
    technologies: ["Express", "Node.js"],
    description: "Create routes, middleware, request handlers, and a clean Express application.",
  },
  {
    id: "node-express-video",
    thumbnail: "/images/skillforge/hero-ethereal-ai.png",
    title: "Node.js and Express.js Full Course",
    source: "freeCodeCamp.org",
    type: "YouTube Tutorial",
    difficulty: "Beginner",
    estimatedTime: "8 hours",
    url: "https://www.youtube.com/watch?v=Oe421EPjeBE",
    technologies: ["Node.js", "Express", "JavaScript"],
    description:
      "A long-form, project-focused introduction to building APIs with Node.js and Express.",
  },
  {
    id: "mongodb-node-path",
    thumbnail: "/images/skillforge/dashboard-ethereal-banner.png",
    title: "MongoDB Node.js Developer Path",
    source: "MongoDB University",
    type: "Online Course",
    difficulty: "Intermediate",
    estimatedTime: "13 hours",
    url: "https://learn.mongodb.com/learning-paths/mongodb-nodejs-developer-path",
    technologies: ["MongoDB", "Node.js"],
    description: "Official learning path covering Atlas, CRUD, aggregation, and application integration.",
  },
  {
    id: "python-tutorial",
    thumbnail: "/images/skillforge/hero-ethereal-ai.png",
    title: "The Python Tutorial",
    source: "Python",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "8 hours",
    url: "https://docs.python.org/3/tutorial/",
    technologies: ["Python"],
    description: "Language fundamentals, data structures, modules, errors, classes, and environments.",
  },
  {
    id: "pandas-tutorials",
    thumbnail: "/images/skillforge/features-ethereal-waves-light.png",
    title: "Pandas Getting Started Tutorials",
    source: "pandas",
    type: "Online Course",
    difficulty: "Beginner",
    estimatedTime: "5 hours",
    url: "https://pandas.pydata.org/docs/getting_started/intro_tutorials/",
    technologies: ["Python", "pandas", "Data Analysis"],
    description: "Hands-on tabular data loading, cleaning, selection, plotting, and reshaping.",
  },
  {
    id: "sklearn-start",
    thumbnail: "/images/skillforge/chat-subtle-neural-grid.png",
    title: "Getting Started with scikit-learn",
    source: "scikit-learn",
    type: "Official Documentation",
    difficulty: "Intermediate",
    estimatedTime: "3 hours",
    url: "https://scikit-learn.org/stable/getting_started.html",
    technologies: ["Python", "Machine Learning", "scikit-learn"],
    description: "Fit, preprocess, evaluate, and tune reproducible machine-learning pipelines.",
  },
  {
    id: "pytorch-tutorials",
    thumbnail: "/images/skillforge/hero-ethereal-ai-light.png",
    title: "PyTorch Tutorials",
    source: "PyTorch",
    type: "Official Documentation",
    difficulty: "Advanced",
    estimatedTime: "10 hours",
    url: "https://docs.pytorch.org/tutorials/",
    technologies: ["Python", "AI", "PyTorch"],
    description: "Practical neural-network, data-loading, training, and deployment tutorials.",
  },
  {
    id: "android-training",
    thumbnail: "/images/skillforge/dashboard-ethereal-banner-light.png",
    title: "Android Basics with Compose",
    source: "Android Developers",
    type: "Online Course",
    difficulty: "Beginner",
    estimatedTime: "15 hours",
    url: "https://developer.android.com/courses/android-basics-compose/course",
    technologies: ["Kotlin", "Android", "Jetpack Compose"],
    description: "Official project-based Android training with Kotlin and modern Compose UI.",
  },
  {
    id: "react-native-docs",
    thumbnail: "/images/skillforge/features-ethereal-waves.png",
    title: "React Native Fundamentals",
    source: "React Native",
    type: "Official Documentation",
    difficulty: "Intermediate",
    estimatedTime: "5 hours",
    url: "https://reactnative.dev/docs/getting-started",
    technologies: ["React Native", "React", "JavaScript"],
    description: "Cross-platform components, styling, navigation concepts, and native capabilities.",
  },
  {
    id: "owasp-top-ten",
    thumbnail: "/images/skillforge/footer-ethereal-constellation.png",
    title: "OWASP Top 10",
    source: "OWASP",
    type: "Article",
    difficulty: "Intermediate",
    estimatedTime: "2 hours",
    url: "https://owasp.org/www-project-top-ten/",
    technologies: ["Cyber Security", "Web Security"],
    description: "The standard awareness guide for the most critical web application security risks.",
  },
  {
    id: "portswigger-academy",
    thumbnail: "/images/skillforge/chat-subtle-neural-grid.png",
    title: "Web Security Academy",
    source: "PortSwigger",
    type: "Practice Platform",
    difficulty: "Intermediate",
    estimatedTime: "20 hours",
    url: "https://portswigger.net/web-security",
    technologies: ["Cyber Security", "Web Security"],
    description: "Interactive labs for authentication, injection, access control, and browser security.",
  },
  {
    id: "docker-start",
    thumbnail: "/images/skillforge/dashboard-ethereal-banner.png",
    title: "Docker Get Started",
    source: "Docker",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "4 hours",
    url: "https://docs.docker.com/get-started/",
    technologies: ["Docker", "DevOps"],
    description: "Images, containers, multi-container apps, persistence, and Compose fundamentals.",
  },
  {
    id: "kubernetes-basics",
    thumbnail: "/images/skillforge/hero-ethereal-ai.png",
    title: "Kubernetes Basics",
    source: "Kubernetes",
    type: "Online Course",
    difficulty: "Intermediate",
    estimatedTime: "5 hours",
    url: "https://kubernetes.io/docs/tutorials/kubernetes-basics/",
    technologies: ["Kubernetes", "DevOps", "Cloud"],
    description: "Deploy, scale, update, and debug containerized applications on Kubernetes.",
  },
  {
    id: "leetcode-interview",
    thumbnail: "/images/skillforge/empty-learning-journey.png",
    title: "Top Interview 150",
    source: "LeetCode",
    type: "Coding Challenge",
    difficulty: "Intermediate",
    estimatedTime: "30 hours",
    url: "https://leetcode.com/studyplan/top-interview-150/",
    technologies: ["Algorithms", "Data Structures", "Interview"],
    description: "A focused collection of common data-structure and algorithm interview problems.",
  },
  {
    id: "figma-design-basics",
    thumbnail: "/images/skillforge/features-ethereal-waves-light.png",
    title: "Figma Design Basics",
    source: "Figma",
    type: "Official Documentation",
    difficulty: "Beginner",
    estimatedTime: "3 hours",
    url: "https://help.figma.com/hc/en-us/categories/360002051613-Design-basics",
    technologies: ["Figma", "UI/UX Design"],
    description: "Official guidance for interface design, layout, components, and prototyping.",
  },
  {
    id: "aws-cloud-practitioner",
    thumbnail: "/images/skillforge/dashboard-ethereal-banner-light.png",
    title: "AWS Cloud Practitioner Essentials",
    source: "AWS Skill Builder",
    type: "Online Course",
    difficulty: "Beginner",
    estimatedTime: "6 hours",
    url: "https://skillbuilder.aws/learn",
    technologies: ["AWS", "Cloud"],
    description: "Cloud concepts, core AWS services, security, architecture, and operations.",
  },
  {
    id: "playwright-intro",
    thumbnail: "/images/skillforge/chat-subtle-neural-grid-light.png",
    title: "Playwright Introduction",
    source: "Playwright",
    type: "Official Documentation",
    difficulty: "Intermediate",
    estimatedTime: "3 hours",
    url: "https://playwright.dev/docs/intro",
    technologies: ["Playwright", "Testing", "TypeScript"],
    description: "Reliable browser automation, test isolation, assertions, fixtures, and reporting.",
  },
];
