export type PublicRoadmapStep = {
  title: string;
  summary: string;
  estimatedHours: number;
  objectives: string[];
  resourceIds: string[];
};

export type PublicRoadmap = {
  slug: string;
  careerTitle: string;
  category: "Web Development" | "Mobile" | "Design" | "Data & AI" | "Security" | "Cloud & DevOps" | "Quality";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  durationWeeks: number;
  topicCount: number;
  popularity: number;
  createdAt: string;
  coverImage: string;
  technologies: string[];
  keywords: string[];
  description: string;
  learningOutcomes: string[];
  steps: PublicRoadmapStep[];
  author: "SkillForge AI";
};

export const publicRoadmaps: PublicRoadmap[] = [
  {
    slug: "frontend-developer",
    careerTitle: "Frontend Developer",
    category: "Web Development",
    difficulty: "Beginner",
    durationWeeks: 16,
    topicCount: 32,
    popularity: 98,
    createdAt: "2026-07-12T00:00:00.000Z",
    coverImage: "/images/skillforge/hero-ethereal-ai-light.png",
    technologies: ["HTML", "CSS", "JavaScript", "TypeScript", "React", "Next.js"],
    keywords: ["frontend", "responsive", "web", "components", "portfolio"],
    description: "Move from web foundations to production-ready React and Next.js interfaces with accessible portfolio work.",
    learningOutcomes: ["Build accessible responsive interfaces", "Model React applications with TypeScript", "Ship and explain a polished frontend portfolio"],
    author: "SkillForge AI",
    steps: [
      { title: "Web foundations", summary: "Create semantic, responsive pages and strengthen core JavaScript.", estimatedHours: 42, objectives: ["Use semantic HTML and accessible forms", "Build responsive layouts", "Write modern JavaScript modules"], resourceIds: ["mdn-web-foundations", "javascript-guide"] },
      { title: "React and TypeScript", summary: "Build component systems with predictable typed state.", estimatedHours: 55, objectives: ["Compose reusable React components", "Type props, events, and state", "Manage asynchronous server state"], resourceIds: ["react-learn", "typescript-handbook", "tanstack-query-docs"] },
      { title: "Next.js portfolio delivery", summary: "Ship optimized full-featured interfaces and portfolio case studies.", estimatedHours: 50, objectives: ["Use App Router conventions", "Handle data and loading states", "Deploy a recruiter-ready project"], resourceIds: ["nextjs-course", "leetcode-interview"] },
    ],
  },
  {
    slug: "backend-developer",
    careerTitle: "Backend Developer",
    category: "Web Development",
    difficulty: "Intermediate",
    durationWeeks: 18,
    topicCount: 36,
    popularity: 94,
    createdAt: "2026-07-10T00:00:00.000Z",
    coverImage: "/images/skillforge/footer-ethereal-constellation-light.png",
    technologies: ["Node.js", "Express", "TypeScript", "MongoDB", "REST API"],
    keywords: ["backend", "api", "database", "authentication", "server"],
    description: "Design secure, maintainable APIs with Node.js, Express, MongoDB, authentication, and production diagnostics.",
    learningOutcomes: ["Design REST APIs around clear contracts", "Model and query MongoDB effectively", "Secure and operate an authenticated backend"],
    author: "SkillForge AI",
    steps: [
      { title: "Node.js runtime and HTTP", summary: "Understand asynchronous server execution and HTTP boundaries.", estimatedHours: 38, objectives: ["Use modules and asynchronous patterns", "Handle HTTP requests and errors", "Structure services by responsibility"], resourceIds: ["node-learn", "typescript-handbook"] },
      { title: "Express API engineering", summary: "Create validated routes, middleware, authentication, and consistent errors.", estimatedHours: 48, objectives: ["Design REST resources", "Validate untrusted input", "Apply authentication and authorization"], resourceIds: ["express-guide", "node-express-video", "owasp-top-ten"] },
      { title: "MongoDB and production readiness", summary: "Persist domain data and prepare the service for production.", estimatedHours: 55, objectives: ["Design documents and indexes", "Build aggregations", "Document and test API behavior"], resourceIds: ["mongodb-node-path", "leetcode-interview"] },
    ],
  },
  {
    slug: "full-stack-developer",
    careerTitle: "Full Stack Developer",
    category: "Web Development",
    difficulty: "Intermediate",
    durationWeeks: 24,
    topicCount: 48,
    popularity: 100,
    createdAt: "2026-07-15T00:00:00.000Z",
    coverImage: "/images/skillforge/dashboard-ethereal-banner-light.png",
    technologies: ["React", "Next.js", "Node.js", "Express", "MongoDB", "TypeScript"],
    keywords: ["mern", "full stack", "saas", "authentication", "deployment"],
    description: "Build complete SaaS products across UI, APIs, databases, authentication, testing, and deployment.",
    learningOutcomes: ["Connect typed clients and APIs", "Implement secure end-to-end product workflows", "Deploy and present a substantial SaaS application"],
    author: "SkillForge AI",
    steps: [
      { title: "Typed frontend systems", summary: "Build responsive React interfaces and reliable server-state flows.", estimatedHours: 65, objectives: ["Create reusable UI patterns", "Use TypeScript across forms and queries", "Handle loading, errors, and cache updates"], resourceIds: ["react-learn", "typescript-handbook", "tanstack-query-docs"] },
      { title: "APIs, data, and identity", summary: "Create secure Express services and MongoDB models.", estimatedHours: 80, objectives: ["Model user-scoped resources", "Secure protected endpoints", "Maintain clean controller and service boundaries"], resourceIds: ["node-learn", "express-guide", "mongodb-node-path"] },
      { title: "Product integration and delivery", summary: "Join every layer into a tested, observable portfolio product.", estimatedHours: 70, objectives: ["Integrate Next.js with the API", "Test critical workflows", "Deploy and document architecture"], resourceIds: ["nextjs-course", "playwright-intro", "docker-start"] },
    ],
  },
  {
    slug: "react-native-developer",
    careerTitle: "React Native Developer",
    category: "Mobile",
    difficulty: "Intermediate",
    durationWeeks: 18,
    topicCount: 34,
    popularity: 86,
    createdAt: "2026-07-05T00:00:00.000Z",
    coverImage: "/images/skillforge/features-ethereal-waves-light.png",
    technologies: ["React Native", "React", "TypeScript", "Mobile"],
    keywords: ["ios", "android", "cross platform", "mobile app"],
    description: "Transfer React skills into polished cross-platform applications with navigation, data, device APIs, and release preparation.",
    learningOutcomes: ["Build cross-platform mobile interfaces", "Manage navigation and remote data", "Prepare a production mobile release"],
    author: "SkillForge AI",
    steps: [
      { title: "React mobile foundations", summary: "Learn native components, mobile layouts, and platform-aware interaction.", estimatedHours: 45, objectives: ["Compose native screens", "Build adaptive mobile layouts", "Handle touch and keyboard interaction"], resourceIds: ["react-learn", "react-native-docs"] },
      { title: "Navigation and application data", summary: "Structure multi-screen apps with reliable asynchronous data.", estimatedHours: 52, objectives: ["Design navigation flows", "Cache remote data", "Handle offline and error states"], resourceIds: ["react-native-docs", "typescript-handbook", "tanstack-query-docs"] },
      { title: "Portfolio mobile product", summary: "Integrate device features, testing, performance, and release workflows.", estimatedHours: 58, objectives: ["Use a device capability", "Profile application performance", "Create store-ready release assets"], resourceIds: ["react-native-docs", "playwright-intro"] },
    ],
  },
  {
    slug: "android-kotlin-developer",
    careerTitle: "Android Developer",
    category: "Mobile",
    difficulty: "Beginner",
    durationWeeks: 20,
    topicCount: 38,
    popularity: 82,
    createdAt: "2026-06-29T00:00:00.000Z",
    coverImage: "/images/skillforge/features-ethereal-waves.png",
    technologies: ["Kotlin", "Android", "Jetpack Compose"],
    keywords: ["android", "kotlin", "compose", "mobile"],
    description: "Learn Kotlin and modern Android development through Compose-driven apps, data persistence, networking, and architecture.",
    learningOutcomes: ["Write clear Kotlin application code", "Build Compose interfaces", "Structure an Android app with modern architecture"],
    author: "SkillForge AI",
    steps: [
      { title: "Kotlin and Android basics", summary: "Learn Kotlin syntax, Android project structure, and application lifecycle.", estimatedHours: 48, objectives: ["Use Kotlin language fundamentals", "Navigate Android tooling", "Explain application lifecycle"], resourceIds: ["android-training"] },
      { title: "Compose UI and state", summary: "Create responsive, accessible screens with state-driven Compose.", estimatedHours: 58, objectives: ["Compose reusable UI", "Manage screen state", "Build navigation flows"], resourceIds: ["android-training"] },
      { title: "Data-driven Android portfolio", summary: "Integrate networking, local persistence, testing, and release preparation.", estimatedHours: 62, objectives: ["Consume a remote API", "Persist offline data", "Test and package an application"], resourceIds: ["android-training", "leetcode-interview"] },
    ],
  },
  {
    slug: "ui-ux-designer",
    careerTitle: "UI/UX Designer",
    category: "Design",
    difficulty: "Beginner",
    durationWeeks: 14,
    topicCount: 26,
    popularity: 89,
    createdAt: "2026-07-08T00:00:00.000Z",
    coverImage: "/images/skillforge/footer-ethereal-constellation-light.png",
    technologies: ["Figma", "UI/UX Design", "Prototyping", "Accessibility"],
    keywords: ["design", "research", "wireframe", "prototype", "case study"],
    description: "Build research-backed product design skills and a portfolio case study from problem framing through validated prototype.",
    learningOutcomes: ["Plan lightweight user research", "Create accessible visual systems", "Present a complete product case study"],
    author: "SkillForge AI",
    steps: [
      { title: "Research and problem framing", summary: "Turn ambiguous problems into evidence-backed user needs.", estimatedHours: 35, objectives: ["Plan interviews and competitive reviews", "Synthesize patterns", "Write a focused problem statement"], resourceIds: ["figma-design-basics"] },
      { title: "Interaction and visual systems", summary: "Design flows, wireframes, components, hierarchy, and accessible states.", estimatedHours: 48, objectives: ["Map user flows", "Create a component system", "Apply accessible contrast and interaction states"], resourceIds: ["figma-design-basics", "mdn-web-foundations"] },
      { title: "Prototype and portfolio case study", summary: "Test a prototype and communicate decisions through outcomes.", estimatedHours: 42, objectives: ["Build an interactive prototype", "Run usability tests", "Publish a concise case study"], resourceIds: ["figma-design-basics"] },
    ],
  },
  {
    slug: "ai-engineer",
    careerTitle: "AI Engineer",
    category: "Data & AI",
    difficulty: "Advanced",
    durationWeeks: 28,
    topicCount: 52,
    popularity: 96,
    createdAt: "2026-07-14T00:00:00.000Z",
    coverImage: "/images/skillforge/hero-ethereal-ai.png",
    technologies: ["Python", "Machine Learning", "PyTorch", "LLM"],
    keywords: ["artificial intelligence", "ml", "deep learning", "llm", "rag"],
    description: "Progress from Python and machine-learning foundations to neural networks, LLM applications, evaluation, and deployment.",
    learningOutcomes: ["Build reproducible ML pipelines", "Train and evaluate neural models", "Ship an evaluated context-aware AI application"],
    author: "SkillForge AI",
    steps: [
      { title: "Python and ML foundations", summary: "Build a strong data, statistics, preprocessing, and classical ML base.", estimatedHours: 85, objectives: ["Manipulate data with Python", "Train baseline models", "Evaluate without leakage"], resourceIds: ["python-tutorial", "pandas-tutorials", "sklearn-start"] },
      { title: "Deep learning systems", summary: "Understand tensors, optimization, neural architectures, and experiment tracking.", estimatedHours: 95, objectives: ["Train a neural network", "Diagnose overfitting", "Make experiments reproducible"], resourceIds: ["pytorch-tutorials", "sklearn-start"] },
      { title: "LLM product engineering", summary: "Create grounded AI workflows with structured output, evaluation, and safe deployment.", estimatedHours: 100, objectives: ["Design robust prompts and schemas", "Ground responses in relevant context", "Evaluate quality, latency, and failure modes"], resourceIds: ["pytorch-tutorials", "docker-start"] },
    ],
  },
  {
    slug: "data-analyst",
    careerTitle: "Data Analyst",
    category: "Data & AI",
    difficulty: "Beginner",
    durationWeeks: 16,
    topicCount: 30,
    popularity: 91,
    createdAt: "2026-07-03T00:00:00.000Z",
    coverImage: "/images/skillforge/dashboard-ethereal-banner-light.png",
    technologies: ["Python", "pandas", "SQL", "Data Visualization"],
    keywords: ["analytics", "dashboard", "data cleaning", "insights"],
    description: "Develop practical data-cleaning, analysis, visualization, and communication skills through decision-focused projects.",
    learningOutcomes: ["Clean and validate tabular data", "Create honest analytical visualizations", "Communicate actionable findings"],
    author: "SkillForge AI",
    steps: [
      { title: "Python and tabular data", summary: "Build repeatable workflows for loading, cleaning, joining, and validating data.", estimatedHours: 48, objectives: ["Use Python fundamentals", "Transform dataframes", "Document data-quality assumptions"], resourceIds: ["python-tutorial", "pandas-tutorials"] },
      { title: "Analysis and visualization", summary: "Answer concrete questions with aggregation, statistics, and appropriate charts.", estimatedHours: 52, objectives: ["Perform exploratory analysis", "Select honest visual encodings", "Explain uncertainty and limitations"], resourceIds: ["pandas-tutorials", "sklearn-start"] },
      { title: "Portfolio analytics case study", summary: "Deliver a reproducible analysis and stakeholder-ready dashboard narrative.", estimatedHours: 45, objectives: ["Define business metrics", "Build a clear report", "Present recommendations with evidence"], resourceIds: ["pandas-tutorials"] },
    ],
  },
  {
    slug: "cyber-security-analyst",
    careerTitle: "Cyber Security Analyst",
    category: "Security",
    difficulty: "Intermediate",
    durationWeeks: 20,
    topicCount: 40,
    popularity: 90,
    createdAt: "2026-06-27T00:00:00.000Z",
    coverImage: "/images/skillforge/chat-subtle-neural-grid.png",
    technologies: ["Cyber Security", "Web Security", "Linux", "Networking"],
    keywords: ["security", "owasp", "vulnerability", "soc", "penetration testing"],
    description: "Build defensive fundamentals, web-security analysis, hands-on vulnerability testing, and clear remediation reporting.",
    learningOutcomes: ["Recognize common application risks", "Test vulnerabilities in safe labs", "Write useful findings and remediation guidance"],
    author: "SkillForge AI",
    steps: [
      { title: "Security foundations and threat thinking", summary: "Understand assets, threats, controls, networking, and secure design principles.", estimatedHours: 50, objectives: ["Model basic threats", "Explain core network boundaries", "Apply least privilege"], resourceIds: ["owasp-top-ten"] },
      { title: "Web application security labs", summary: "Practice identifying and exploiting common vulnerabilities in legal lab environments.", estimatedHours: 72, objectives: ["Test access control", "Identify injection risks", "Analyze authentication weaknesses"], resourceIds: ["owasp-top-ten", "portswigger-academy"] },
      { title: "Assessment and remediation portfolio", summary: "Conduct a scoped assessment and produce professional evidence and fixes.", estimatedHours: 55, objectives: ["Document reproducible findings", "Prioritize risk", "Recommend concrete remediation"], resourceIds: ["portswigger-academy", "node-learn"] },
    ],
  },
  {
    slug: "devops-engineer",
    careerTitle: "DevOps Engineer",
    category: "Cloud & DevOps",
    difficulty: "Intermediate",
    durationWeeks: 18,
    topicCount: 35,
    popularity: 88,
    createdAt: "2026-07-01T00:00:00.000Z",
    coverImage: "/images/skillforge/footer-ethereal-constellation.png",
    technologies: ["Docker", "Kubernetes", "CI/CD", "Cloud"],
    keywords: ["devops", "containers", "deployment", "automation", "observability"],
    description: "Learn reproducible delivery through containers, CI/CD, Kubernetes, observability, and operational reliability.",
    learningOutcomes: ["Containerize multi-service applications", "Automate tested deployments", "Operate and diagnose a Kubernetes workload"],
    author: "SkillForge AI",
    steps: [
      { title: "Containers and reproducible environments", summary: "Package applications and dependencies into portable, secure images.", estimatedHours: 45, objectives: ["Build efficient images", "Use Compose for local systems", "Manage configuration safely"], resourceIds: ["docker-start"] },
      { title: "Continuous delivery", summary: "Automate quality gates, builds, releases, and safe deployment workflows.", estimatedHours: 50, objectives: ["Design a CI pipeline", "Cache dependencies safely", "Create rollback-aware releases"], resourceIds: ["docker-start", "playwright-intro"] },
      { title: "Kubernetes operations", summary: "Deploy, scale, update, observe, and troubleshoot container workloads.", estimatedHours: 62, objectives: ["Deploy Kubernetes objects", "Roll out updates", "Diagnose failed workloads"], resourceIds: ["kubernetes-basics", "docker-start"] },
    ],
  },
  {
    slug: "cloud-engineer",
    careerTitle: "Cloud Engineer",
    category: "Cloud & DevOps",
    difficulty: "Intermediate",
    durationWeeks: 22,
    topicCount: 42,
    popularity: 84,
    createdAt: "2026-06-25T00:00:00.000Z",
    coverImage: "/images/skillforge/dashboard-ethereal-banner.png",
    technologies: ["AWS", "Cloud", "Docker", "Kubernetes"],
    keywords: ["cloud", "aws", "infrastructure", "networking", "availability"],
    description: "Learn cloud architecture, identity, networking, compute, storage, containers, automation, and resilient system design.",
    learningOutcomes: ["Explain core cloud architecture tradeoffs", "Deploy a secure containerized workload", "Design for reliability and cost awareness"],
    author: "SkillForge AI",
    steps: [
      { title: "Cloud and infrastructure foundations", summary: "Understand regions, networking, identity, compute, storage, and shared responsibility.", estimatedHours: 58, objectives: ["Select appropriate cloud services", "Apply identity boundaries", "Design basic virtual networking"], resourceIds: ["aws-cloud-practitioner"] },
      { title: "Container cloud delivery", summary: "Package services and deploy scalable workloads with managed infrastructure.", estimatedHours: 66, objectives: ["Containerize services", "Deploy orchestrated workloads", "Manage secrets and configuration"], resourceIds: ["docker-start", "kubernetes-basics"] },
      { title: "Reliable architecture portfolio", summary: "Design, automate, observe, and cost-review a resilient cloud application.", estimatedHours: 68, objectives: ["Plan for failure", "Add monitoring and alerts", "Document cost and security decisions"], resourceIds: ["aws-cloud-practitioner", "kubernetes-basics"] },
    ],
  },
  {
    slug: "qa-automation-engineer",
    careerTitle: "QA Automation Engineer",
    category: "Quality",
    difficulty: "Beginner",
    durationWeeks: 14,
    topicCount: 28,
    popularity: 79,
    createdAt: "2026-06-21T00:00:00.000Z",
    coverImage: "/images/skillforge/chat-subtle-neural-grid-light.png",
    technologies: ["TypeScript", "Playwright", "API Testing", "CI/CD"],
    keywords: ["testing", "automation", "quality", "e2e", "playwright"],
    description: "Build a quality-engineering mindset and automate reliable browser, API, regression, and CI test workflows.",
    learningOutcomes: ["Design valuable test coverage", "Build stable Playwright suites", "Integrate automated quality gates into CI"],
    author: "SkillForge AI",
    steps: [
      { title: "Testing foundations", summary: "Learn risk-based testing, test design, bug communication, and web fundamentals.", estimatedHours: 35, objectives: ["Write precise test cases", "Prioritize risks", "Report reproducible defects"], resourceIds: ["mdn-web-foundations", "javascript-guide"] },
      { title: "Browser and API automation", summary: "Create isolated, maintainable Playwright tests and API checks.", estimatedHours: 48, objectives: ["Use resilient locators", "Control test data", "Test critical API contracts"], resourceIds: ["playwright-intro", "typescript-handbook"] },
      { title: "Continuous quality portfolio", summary: "Integrate test suites into CI and publish useful results.", estimatedHours: 40, objectives: ["Run tests in CI", "Diagnose flaky tests", "Present quality metrics and coverage decisions"], resourceIds: ["playwright-intro", "docker-start"] },
    ],
  },
];
